# Generated by Django 4.1.3 on 2022-12-27 14:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_section_threads_section_threads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
