# Generated by Django 4.1.3 on 2022-12-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
